name: runDummyPost
on: [push, pull_request]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: get Posts Detail
        uses: grafana/k6-action@v0.2.0
        with:
          filename: TC-getPostsDetail.js
          flags: --vus 1 --duration 1s
          
      - name: get Posts Detail
        uses: grafana/k6-action@v0.2.0
        with:
          filename: getPosts.js
          flags: --vus 1 --duration 1s
